.\" QPrompt manpage
.TH QPrompt 1 "Nov 2023" "1.2" "QPrompt's command line documentation"
.SH NAME
qprompt \- Teleprompter software for all video creators.
.SH SYNOPSIS
qprompt [\-options] [file]
.SH DESCRIPTION
Personal teleprompter software for all video creators. Built with ease of use, productivity, control accuracy, and smooth performance in mind.
.SH OPTIONS
.SS
.SS Arguments:
.TP
.B file
Document to open
.SS Options:
.TP
.B  \-q,  \-\-qgs_ignore
Forces QPrompt to ignore the QSG_RENDER_LOOP environment variable, which may be needed to enable the screen projections feature.
.SS
.SS Generic options:
.TP
.B  \-h,  \-\-help
Show help about options.
.TP
.B  \-\-help\-all
Show help including Qt specific options.
.TP
.B \-v,  \-\-version
Show version information.
.SH SEE ALSO
Join our community at:
.BR https://qprompt.app/
.br
Help us translate to your language at:
.BR https://l10n.qprompt.app/
.br
.SH AUTHORS
.nf
Javier O. Cordero Pérez
.br
